services:
  frontend:
    image: frontend
    ports:
      - 4200:4200
  backend:
    image: backend
    restart: on-failure
    ports:
      - "4040:4040"
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
